require("plugins_config.telescope")
require("plugins_config.lsp")
require("plugins_config.cmp")
require("plugins_config.git")
require("plugins_config.treesitter")
require("plugins_config.dap")
require("plugins_config.lualine")
